<?php
/**
 * Copyright © 2024 Line. All rights reserved.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div>
    <div>
        <h4>¿Qué es Line "Compras Verificadas"?</h4>
        <p>Es una solución de prevención de fraude que garantiza que el titular
            de la tarjeta de crédito/debito a participar de la transacción,
            para saber mas ingresá en
            <a href="https://line.net.ar/" target="_blank">https://line.net.ar/</a>
        </p>
    </div>
    <div>
        <h4>¿Cómo Funciona?</h4>
        <p>Cuando realizas una compra que necesita verificación,
            te enviaremos un código de 6 dígitos que vas a ver reflejado
            en la descripción del consumo en tu homebanking o app de tu banco,
            este código puede tardar hasta 72 horas en aparecer en la descripcion de tu consumo,
            segui las instrucciones que te enviamos por mail para verificar tu compra.</p>
        <p>Este paso es esencial para proteger tu compra y
            evitar cualquier uso no autorizado de tu tarjeta de crédito/débito.</p>
    </div>
</div>
